# for module compiling
import os
Import('RTT_ROOT')
Import('rtconfig')
from building import *

cwd = GetCurrentDir()

src = Glob('*.c')

CPPPATH = [cwd, str(Dir('#'))]

group = DefineGroup('inc_rtt', src, depend = [''], CPPPATH = CPPPATH)

Return('group')